workers_dev = true

name = "gerenciador-de-gastos-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "gerenciador_de_gastos"
database_id = "1246ece6-79a7-4b4f-8101-227be221cdf1"
migrations_dir = "migrations"

[vars]
CORS_ORIGINS = "http://localhost:5173,http://127.0.0.1:5173,https://delcidesneto.github.io"
ADMIN_EMAIL = "delcides.c.c.neto@gmail.com"

# Secrets (definidos via `wrangler secret put`):
# JWT_SECRET
# ADMIN_PASSWORD
